# SPDX-FileCopyrightText: 2025 Simon Wendel
# SPDX-License-Identifier: CC0-1.0

name: REUSE Compliance Check

on:
  workflow_call:

jobs:
  reuse-compliance-check:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v5