# SPDX-FileCopyrightText: 2025 Simon Wendel
# SPDX-License-Identifier: CC0-1.0

name: Build+Test .NET

on:
  workflow_call:

jobs:
  build-then-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal