# SPDX-FileCopyrightText: 2025 Simon Wendel
# SPDX-License-Identifier: CC0-1.0

name: Build+Test .NET (main)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  reuse-compliance-check:
    uses: ./.github/workflows/reuse-compliance.yml
  build-then-test:
    uses: ./.github/workflows/build-then-test.yml